baseURL = "https://jmbruel.github.io/scilog-site"
languageCode = 'fr-fr'
title = 'GdR SciLog'
theme = "mon-theme"
canonifyURLs = true
enableRobotsTXT = true

[taxonomies]
  archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
